In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#234567890
import numpy as np
import torch

## Initializing Tensors

In [2]:
x = torch.tensor([[1, 2]])
y = torch.tensor([[1], [2]])
print(x.shape)
print(y.shape)
print(x.dtype)

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
x = torch.tensor([False, 1, 2.])
x

tensor([0., 1., 2.])

In [4]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.randint(low=0, high=10, size=(3, 2))

tensor([[4, 5],
        [5, 8],
        [8, 5]])

In [7]:
torch.rand(2, 4)

tensor([[0.5089, 0.3793, 0.3462, 0.2339],
        [0.2929, 0.6800, 0.4203, 0.4143]])

In [8]:
torch.randn((3, 4))  # normal

tensor([[ 0.7995,  1.4468,  1.8945,  0.1164],
        [ 1.2885,  0.3013, -0.4342,  0.0116],
        [-1.0550,  0.1686, -0.8123,  0.1442]])

In [9]:
x = np.array([[10, 20, 30], [2, 3, 4]])
y = torch.tensor(x)
y

tensor([[10, 20, 30],
        [ 2,  3,  4]])

In [10]:
type(x), type(y)

(numpy.ndarray, torch.Tensor)

## Operations on Tensors

In [11]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
10 * x

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [13]:
y = x + 10
y

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [14]:
y.shape

torch.Size([2, 4])

In [15]:
y = y.view(4, 2)  # reshape
y

tensor([[11, 12],
        [13, 14],
        [15, 16],
        [17, 18]])

In [16]:
x = torch.randn(3, 1, 3)
z1 =  torch.squeeze(x, 1)
z2 = torch.squeeze(x)  # only one possible dim to squeeze out
x.shape, z1.shape, z2.shape

(torch.Size([3, 1, 3]), torch.Size([3, 3]), torch.Size([3, 3]))

In [17]:
x = torch.randn(3, 3)
z1 = x.unsqueeze(0)
z2 = x.unsqueeze(1)
x.shape, z1.shape, z2.shape

(torch.Size([3, 3]), torch.Size([1, 3, 3]), torch.Size([3, 1, 3]))

In [18]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
x @ y

tensor([[150, 160],
        [374, 400]])

In [19]:
torch.matmul(x, y)

tensor([[150, 160],
        [374, 400]])