In [11]:
import numpy as np
import torch

## Initializing Tensors

In [2]:
x = torch.tensor([[1, 2]])
y = torch.tensor([[1], [2]])
print(x.shape)
print(y.shape)
print(x.dtype)

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
x = torch.tensor([False, 1, 2.])
x

tensor([0., 1., 2.])

In [4]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.randint(low=0, high=10, size=(3, 2))

tensor([[5, 7],
        [9, 9],
        [8, 2]])

In [9]:
torch.rand(2, 4)

tensor([[0.8123, 0.1612, 0.8300, 0.9663],
        [0.5967, 0.7216, 0.9647, 0.1255]])

In [10]:
torch.randn((3, 4))  # normal

tensor([[-0.4935,  0.7069, -0.7206, -0.7843],
        [-0.7130,  0.9011,  0.3905, -1.7134],
        [-2.1202,  1.3433,  1.9839,  1.4123]])

In [12]:
x = np.array([[10, 20, 30], [2, 3, 4]])
y = torch.tensor(x)
y

tensor([[10, 20, 30],
        [ 2,  3,  4]])

In [13]:
type(x), type(y)

(numpy.ndarray, torch.Tensor)

## Operations on Tensors